Bug Fixes

diff --git a/Cocoa/clean_all b/Cocoa/clean_all
--- a/Cocoa/clean_all
+++ b/Cocoa/clean_all
@@ -1,7 +1,7 @@
 
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not defined'
-    return
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
 fi
 # --------------------------------------------------------------------------------------
 # --------------------------------------------------------------------------------------
