Update and BugFixes

diff --git a/Cocoa/setup_cocoa_installation_packages b/Cocoa/setup_cocoa_installation_packages
--- a/Cocoa/setup_cocoa_installation_packages
+++ b/Cocoa/setup_cocoa_installation_packages
@@ -125,27 +125,28 @@ else
 fi
 
 if [ -n "${CFLAGS}" ]; then
-    export OLD_CFLAGS=$CFLAGS
+  export OLD_CFLAGS=$CFLAGS
 else
-    export OLD_CFLAGS="x"
+  export OLD_CFLAGS="x"
 fi
 
 if [ -n "${INCLUDE_PATH}" ]; then
-    export OLD_INCLUDE_PATH=$INCLUDE_PATH
+  export OLD_INCLUDE_PATH=$INCLUDE_PATH
 else
-    export OLD_INCLUDE_PATH="x"
+  export OLD_INCLUDE_PATH="x"
 fi
 
 if [ -n "${SET_INSTALLATION_OPTIONS}" ]; then
-    source $SET_INSTALLATION_OPTIONS
+  source $SET_INSTALLATION_OPTIONS
 else
-    source set_installation_options
+  source set_installation_options
 fi
 if [ -n "${MINICONDA_INSTALLATION}" ]; then
-    if [ ${CONDA_SHLVL} -ne 1 ]; then
-        echo "MINICONDA_INSTALLATION SET BUT CONDA ENVIRONMENT NOT ACTIVATED"
-        return 1
-    fi
+  if [ ${CONDA_SHLVL} -ne 1 ]; then
+    echo "MINICONDA_INSTALLATION SET BUT CONDA ENVIRONMENT NOT ACTIVATED"
+    source stop_cocoa
+    return 1
+  fi
 fi
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
@@ -218,11 +219,13 @@ if [ $? -ne 0 ]; then
   return 1
 fi
 
-source ./installation_scripts/setup_decompress_files
-if [ $? -ne 0 ]; then
-  echo "FAILED setup_decompress_files SCRIPT" >&2
-  cd $ROOTDIR
-  return 1
+if [ -z "${DEBUG_SKIP_FILE_DECOMPRESSION_SETUP_COCOA}" ]; then
+  source ./installation_scripts/setup_decompress_files
+  if [ $? -ne 0 ]; then
+    echo "FAILED setup_decompress_files SCRIPT" >&2
+    cd $ROOTDIR
+    return 1
+  fi
 fi
 
 source ./installation_scripts/setup_cmake
