Update start_cocoa/stop_cocoa

diff --git a/Cocoa/start_cocoa b/Cocoa/start_cocoa
--- a/Cocoa/start_cocoa
+++ b/Cocoa/start_cocoa
@@ -150,6 +150,10 @@ fi
 # ----------------------------------------------------------------------------
 
 source $ROOTDIR/.local/bin/activate
+if [ $? -ne 0 ]; then
+  echo "COCOA PRIVATE PYTHON ENV ACTIVATION FAILED" >&2
+  return 1
+fi
 
 export PATH=$ROOTDIR/.local/bin:$PATH
 
