Bug Fixes

diff --git a/Cocoa/start_cocoa b/Cocoa/start_cocoa
--- a/Cocoa/start_cocoa
+++ b/Cocoa/start_cocoa
@@ -150,6 +150,11 @@ fi
 # ----------------------------------------------------------------------------
 
 source $ROOTDIR/.local/bin/activate
+if [ $? -ne 0 ]; then
+  echo "COCOA PRIVATE PYTHON ENV ACTIVATION FAILED" >&2
+  source stop_cocoa
+  return 1
+fi
 
 export PATH=$ROOTDIR/.local/bin:$PATH
 
diff --git a/Cocoa/stop_cocoa b/Cocoa/stop_cocoa
--- a/Cocoa/stop_cocoa
+++ b/Cocoa/stop_cocoa
@@ -4,6 +4,9 @@
 # ----------------------------------------------------------------------------
 
 deactivate
+if [ $? -ne 0 ]; then
+  echo "COCOA PRIVATE PYTHON ENV DEACTIVATION FAILED" >&2
+fi
 
 if [ -n "${OLD_OMP_NUM_THREADS}" ]; then
   if [ "${OLD_OMP_NUM_THREADS}" != "x" ]; then
