Bug Fixes

diff --git a/cocoa_installation_libraries/clean_all b/cocoa_installation_libraries/clean_all
--- a/cocoa_installation_libraries/clean_all
+++ b/cocoa_installation_libraries/clean_all
@@ -1,3 +1,8 @@
+if [ -z "${ROOTDIR}" ]; then
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
+fi
+
 rm -rf ./armadillo-10.6.2
 
 rm -rf ./binutils-2.34
@@ -11,6 +16,7 @@ rm -rf ./cmake-3.17.1
 rm -rf ./carma
 
 rm -rf ./fftw-3.3.8
+rm -rf ./fftw-3.3.10/
 
 rm -rf ./gsl-2.6
 
@@ -29,6 +35,9 @@ rm -rf ./spdlog
 rm -rf ./texinfo-6.7
 
 rm -rf ./xz-5.2.5
+rm -f ./xz-5.2.5.tar.gz
 
 rm -rf ./expat241
+
+rm -rf ./cocoa_build
 
