Update pip_cache and some scripts

diff --git a/cocoa_installation_libraries/clean_all b/cocoa_installation_libraries/clean_all
--- a/cocoa_installation_libraries/clean_all
+++ b/cocoa_installation_libraries/clean_all
@@ -1,34 +1,43 @@
-rm -rf ./armadillo-10.6.2
+if [ -z "${ROOTDIR}" ]; then
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
+fi
 
-rm -rf ./binutils-2.34
+cd ${ROOTDIR}/cocoa_installation_libraries
 
-rm -rf ./boost_1_72_0
+rm -rf ./$COCOA_ARMADILLO_DIR
 
-rm -rf ./cfitsio-3.47
+rm -rf ./$COCOA_BINUTILS_DIR
 
-rm -rf ./cmake-3.17.1
+rm -rf ./$COCOA_BOOST_DIR
 
-rm -rf ./carma
+rm -rf ./$COCOA_CFITSIO_DIR
 
-rm -rf ./fftw-3.3.8
+rm -rf ./$COCOA_CMAKE_DIR
 
-rm -rf ./gsl-2.6
+rm -rf ./$COCOA_CARMA_DIR
 
-rm -rf ./gsl-2.7
+rm -rf ./$COCOA_FFTW_DIR
 
-rm -rf ./lapack-3.9.0
+rm -rf ./$COCOA_GSL_DIR
+
+rm -rf ./$COCOA_LAPACK_DIR
 
 rm -rf ./lapack-build
 
-rm -rf ./OpenBLAS
+rm -rf ./$COCOA_OPENBLAS_DIR
 
 rm -rf ./pip_cache
 
-rm -rf ./spdlog
+rm -rf ./$COCOA_SPDLOG_DIR
 
-rm -rf ./texinfo-6.7
+rm -rf ./$COCOA_TEXINFO_DIR
 
-rm -rf ./xz-5.2.5
+rm -rf ./$COCOA_XZ_DIR
 
-rm -rf ./expat241
+rm -rf ./$COCOA_EXPACT_DIR
+
+rm -rf $COCOA_HDF5_DIR1
+
+cd ${ROOTDIR}
 
