BugFixes

diff --git a/Cocoa/installation_scripts/clean_planck b/Cocoa/installation_scripts/clean_planck
--- a/Cocoa/installation_scripts/clean_planck
+++ b/Cocoa/installation_scripts/clean_planck
@@ -1,10 +1,10 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not define'
-    return
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${PYTHON3}" ]; then
-    echo 'ERROR PYTHON3 not define'
-    return
+    echo 'ERROR ENV VARIABLE PYTHON3 IS NOT DEFINED' >&2
+    return 1
 fi
 
 # ----------------------------------------------------------------------------
@@ -12,6 +12,7 @@ fi
 # ------------------------- REMOVE PLANCK LIKELIHOOD -------------------------
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
+echo 'CLEANING PLANCK LIKELIHOOD'
 
 rm -f $ROOTDIR/.local/bin/clik*
 
@@ -56,4 +57,6 @@ else
     unset CLIK_PLUGIN
 fi
 
+echo 'CLEANING PLANCK LIKELIHOOD DONE'
 cd $ROOTDIR
+
diff --git a/Cocoa/installation_scripts/clean_polychord b/Cocoa/installation_scripts/clean_polychord
--- a/Cocoa/installation_scripts/clean_polychord
+++ b/Cocoa/installation_scripts/clean_polychord
@@ -1,9 +1,9 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not define'
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${PYTHON3}" ]; then
-    echo 'ERROR PYTHON3 not define'
+    echo 'ERROR ENV VARIABLE PYTHON3 IS NOT DEFINED' >&2
     return 1
 fi
 
@@ -12,11 +12,14 @@ fi
 # ----------------------------- REMOVE POLYCHORD ------------------------------
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
+echo 'CLEANING POLYCHORD'
 
-rm -rf $ROOTDIR/.local/lib/python3.6/site-packages/pypolychord-1.16-py3.6-linux-x86_64.egg
+rm -rf $ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/pypolychord-1.16-py3.6-linux-x86_64.egg
 
 cd $ROOTDIR/external_modules/code/PolyChordLite/
 
 make clean
 
 cd $ROOTDIR
+
+echo 'CLEANING POLYCHORD DONE'
