Bug Fixes

diff --git a/Cocoa/installation_scripts/clean_planck b/Cocoa/installation_scripts/clean_planck
--- a/Cocoa/installation_scripts/clean_planck
+++ b/Cocoa/installation_scripts/clean_planck
@@ -1,10 +1,10 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not define'
-    return
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${PYTHON3}" ]; then
-    echo 'ERROR PYTHON3 not define'
-    return
+    echo 'ERROR ENV VARIABLE PYTHON3 IS NOT DEFINED' >&2
+    return 1
 fi
 
 # ----------------------------------------------------------------------------
@@ -12,6 +12,7 @@ fi
 # ------------------------- REMOVE PLANCK LIKELIHOOD -------------------------
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
+echo 'CLEANING PLANCK LIKELIHOOD'
 
 rm -f $ROOTDIR/.local/bin/clik*
 
@@ -35,25 +36,5 @@ $PYTHON3 waf clean
 
 $PYTHON3 waf distclean
 
-if [ -n "${OLD_CLIK_PATH}" ]; then
-    export CLIK_PATH=$OLD_CLIK_PATH
-    unset OLD_CLIK_PATH
-else
-    unset CLIK_PATH
-fi
-
-if [ -n "${OLD_CLIK_DATA}" ]; then
-    export CLIK_DATA=$OLD_CLIK_DATA
-    unset OLD_CLIK_DATA
-else
-    unset CLIK_DATA
-fi
-
-if [ -n "${OLD_CLIK_PLUGIN}" ]; then
-    export CLIK_PLUGIN=$OLD_CLIK_PLUGIN
-    unset OLD_CLIK_PLUGIN
-else
-    unset CLIK_PLUGIN
-fi
-
+echo 'CLEANING PLANCK LIKELIHOOD DONE'
 cd $ROOTDIR
