Massive Update - many bash bug fixes

diff --git a/Cocoa/installation_scripts/setup_c_packages b/Cocoa/installation_scripts/setup_c_packages
--- a/Cocoa/installation_scripts/setup_c_packages
+++ b/Cocoa/installation_scripts/setup_c_packages
@@ -1,25 +1,25 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not defined'
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${CXX_COMPILER}" ]; then
-    echo 'ERROR CXX_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE CXX_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${C_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
-    return 1
-fi
-if [ -z "${FORTRAN_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE C_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${CMAKE}" ]; then
-    echo 'ERROR CMAKE not defined'
+    echo 'ERROR ENV VARIABLE MAKE IS NOT DEFINED' >&2
+    return 1
+fi
+if [ -z "${FORTRAN_COMPILER}" ]; then
+    echo 'ERROR ENV VARIABLE FORTRAN_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${MAKE_NUM_THREADS}" ]; then
-    echo 'ERROR MAKE_NUM_THREADS not defined'
+    echo 'ERROR ENV VARIABLE MAKE_NUM_THREADS IS NOT DEFINED' >&2
     return 1
 fi
 
@@ -50,6 +50,7 @@ if [ -z "${IGNORE_C_FFTW_INSTALLATION}" ]; then
       echo "FFTW CONFIGURE RUN DONE"
     else
       echo "FFTW COULD NOT RUN CONFIGURE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
 
@@ -58,6 +59,7 @@ if [ -z "${IGNORE_C_FFTW_INSTALLATION}" ]; then
       echo "FFTW MAKE RUN DONE"
     else
       echo "FFTW COULD NOT RUN MAKE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
 
@@ -66,14 +68,28 @@ if [ -z "${IGNORE_C_FFTW_INSTALLATION}" ]; then
       echo "FFTW MAKE INSTALL RUN DONE"
     else
       echo "FFTW COULD NOT RUN MAKE INSTALL - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
   else
     FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --enable-openmp \
     --prefix=$ROOTDIR/.local --enable-shared=yes --enable-static=yes
-    
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+
     make all
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+
     make install
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
   fi
 
   cd $ROOTDIR
@@ -97,6 +113,7 @@ if [ -z "${IGNORE_C_CFITSIO_INSTALLATION}" ]; then
       echo "CFITSIO CMAKE RUN DONE"
     else
       echo "CFITSIO COULD NOT RUN CMAKE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
 
@@ -105,6 +122,7 @@ if [ -z "${IGNORE_C_CFITSIO_INSTALLATION}" ]; then
       echo "CFITSIO MAKE RUN DONE"
     else
       echo "CFITSIO COULD NOT RUN MAKE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
 
@@ -113,15 +131,29 @@ if [ -z "${IGNORE_C_CFITSIO_INSTALLATION}" ]; then
       echo "CFITSIO MAKE INSTALL RUN DONE"
     else
       echo "CFITSIO COULD NOT RUN MAKE INSTALL - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
   else
     $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
     -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER \
-    -DCMAKE_FC_COMPILER=FORTRAN_COMPILER --log-level=ERROR .
+    -DCMAKE_FC_COMPILER=FORTRAN_COMPILER .
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
 
     make all
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+
     make install
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
   fi
 
   cd $ROOTDIR
@@ -143,6 +175,7 @@ if [ -z "${IGNORE_C_GSL_INSTALLATION}" ]; then
       echo "GSL CONFIGURE RUN DONE"
     else
       echo "GSL COULD NOT RUN CONFIGURE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
 
@@ -151,6 +184,7 @@ if [ -z "${IGNORE_C_GSL_INSTALLATION}" ]; then
       echo "GSL MAKE RUN DONE"
     else
       echo "GSL COULD NOT RUN MAKE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
 
@@ -159,17 +193,54 @@ if [ -z "${IGNORE_C_GSL_INSTALLATION}" ]; then
       echo "MAKE INSTALL GSL OK"
     else
       echo "GSL COULD NOT RUN MAKE INSTALL - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
   else
     CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local --enable-shared=yes \
     --enable-static=yes
-    
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+
     make all
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+    
     make install
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
   fi
 
   cd $ROOTDIR
+fi
+
+# --------------------------------------------------------------------------------------
+# ----------------------------------- EUCLID EMU ---------------------------------------
+# --------------------------------------------------------------------------------------
+
+if [ -z "${DEBUG_PIP_OUTPUT}" ]; then
+  export OUTPUT_PIP_1="/dev/null"
+  export OUTPUT_PIP_2="/dev/null"
+else
+  export OUTPUT_PIP_1="/dev/tty"
+  export OUTPUT_PIP_2="/dev/tty"
+fi
+
+# WE MIGRATED euclidemu2 TO setup_c_packages SCRIPT BECAUSE IT DEPENDS ON GSL-GNU LIB
+env CXX=$CXX_COMPILER CC=$C_COMPILER  $PIP3 install --global-option=build_ext \
+  $ROOTDIR/../cocoa_installation_libraries/euclidemu2-1.2.0 --no-dependencies \
+  --prefix=$ROOTDIR/.local --no-index > ${OUTPUT_PIP_1} 2> ${OUTPUT_PIP_2}
+if [ $? -ne 0 ]; then
+  echo "PROBLEM PIP euclidemul"
+  return 1
+else
+  echo "PIP euclidemul DONE"
 fi
 
 # --------------------------------------------------------------------------------------
diff --git a/Cocoa/installation_scripts/setup_cpp_packages b/Cocoa/installation_scripts/setup_cpp_packages
--- a/Cocoa/installation_scripts/setup_cpp_packages
+++ b/Cocoa/installation_scripts/setup_cpp_packages
@@ -1,25 +1,25 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not defined'
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${CXX_COMPILER}" ]; then
-    echo 'ERROR CXX_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE CXX_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${C_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
-    return 1
-fi
-if [ -z "${FORTRAN_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE C_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${CMAKE}" ]; then
-    echo 'ERROR CMAKE not defined'
+    echo 'ERROR ENV VARIABLE MAKE IS NOT DEFINED' >&2
+    return 1
+fi
+if [ -z "${FORTRAN_COMPILER}" ]; then
+    echo 'ERROR ENV VARIABLE FORTRAN_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${MAKE_NUM_THREADS}" ]; then
-    echo 'ERROR MAKE_NUM_THREADS not defined'
+    echo 'ERROR ENV VARIABLE MAKE_NUM_THREADS IS NOT DEFINED' >&2
     return 1
 fi
 
@@ -48,6 +48,7 @@ if [ -z "${IGNORE_CPP_SPDLOG_INSTALLATION}" ]; then
       echo "SPDLOG CMAKE RUN DONE"
     else
       echo "SPDLOG COULD NOT RUN CMAKE - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
 
@@ -56,6 +57,7 @@ if [ -z "${IGNORE_CPP_SPDLOG_INSTALLATION}" ]; then
       echo "SPDLOG MAKE RUN DONE"
     else
       echo "SPDLOG COULD NOT RUN MAKE - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
 
@@ -64,14 +66,27 @@ if [ -z "${IGNORE_CPP_SPDLOG_INSTALLATION}" ]; then
       echo "SPDLOG MAKE INSTALL RUN DONE"
     else
       echo "SPDLOG COULD NOT RUN MAKE INSTALL - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
   else
     $CMAKE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local -DCMAKE_C_COMPILER=$C_COMPILER \
-    -DCMAKE_CXX_COMPILER=$CXX_COMPILER --log-level=ERROR
+    -DCMAKE_CXX_COMPILER=$CXX_COMPILER .
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
 
     make 
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
     make install
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
   fi
 
   cd $ROOTDIR
@@ -96,6 +111,7 @@ if [ -z "${IGNORE_CPP_ARMA_INSTALLATION}" ]; then
       echo "ARMADILLO CMAKE RUN DONE"
     else
       echo "ARMADILLO COULD NOT RUN CMAKE - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
 
@@ -104,7 +120,8 @@ if [ -z "${IGNORE_CPP_ARMA_INSTALLATION}" ]; then
     if [ $? -eq 0 ]; then
       echo "ARMADILLO MAKE RUN DONE"
     else
-      echo "ARMADILLO COULD RUN MAKE - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      echo "ARMADILLO COULD NOT RUN MAKE - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
 
@@ -113,17 +130,30 @@ if [ -z "${IGNORE_CPP_ARMA_INSTALLATION}" ]; then
       echo "ARMADILLO MAKE INSTALL RUN DONE"
     else
       echo "ARMADILLO COULD NOT RUN MAKE INSTALL - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
   else
     $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
       -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER \
       -DLAPACK_FOUND=YES -DLAPACK_LIBRARIES=$ROOTDIR/.local/lib/liblapack.so \
-      -DBLAS_FOUND=NO --log-level=ERROR .
+      -DBLAS_FOUND=NO .
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
 
     make clean
     make all
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
     make install 
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
   fi
 
   cd $ROOTDIR
@@ -175,9 +205,17 @@ if [ -z "${IGNORE_CPP_BOOST_INSTALLATION}" ]; then
     fi
   else
     ./bootstrap.sh --prefix=$ROOTDIR/.local 
-
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+    
     ./b2 --with=regex install --without-python --without-thread \
     --without-timer --without-mpi --without-atomic
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
   fi
   
   cd $ROOTDIR
diff --git a/Cocoa/installation_scripts/setup_fortran_packages b/Cocoa/installation_scripts/setup_fortran_packages
--- a/Cocoa/installation_scripts/setup_fortran_packages
+++ b/Cocoa/installation_scripts/setup_fortran_packages
@@ -1,25 +1,25 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not defined'
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${CXX_COMPILER}" ]; then
-    echo 'ERROR CXX_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE CXX_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${C_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
-    return 1
-fi
-if [ -z "${FORTRAN_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE C_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${CMAKE}" ]; then
-    echo 'ERROR CMAKE not defined'
+    echo 'ERROR ENV VARIABLE MAKE IS NOT DEFINED' >&2
+    return 1
+fi
+if [ -z "${FORTRAN_COMPILER}" ]; then
+    echo 'ERROR ENV VARIABLE FORTRAN_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${MAKE_NUM_THREADS}" ]; then
-    echo 'ERROR MAKE_NUM_THREADS not defined'
+    echo 'ERROR ENV VARIABLE MAKE_NUM_THREADS IS NOT DEFINED' >&2
     return 1
 fi
 
@@ -47,7 +47,8 @@ if [ -z "${IGNORE_FORTRAN_LAPACK_INSTALLATION}" ]; then
     if [ $? -eq 0 ]; then
       echo "LAPACK CMAKE RUN DONE"
     else
-      echo "LAPACK COULD NOT RUN CMAKE - CHECK SETUP_FORTRAN_PACKAGES SCRIPT" >&2
+      echo "LAPACK COULD NOT RUN CMAKE" >&2
+      cd $ROOTDIR
       return 1
     fi
 
@@ -55,7 +56,8 @@ if [ -z "${IGNORE_FORTRAN_LAPACK_INSTALLATION}" ]; then
     if [ $? -eq 0 ]; then
       echo "LAPACK MAKE RUN DONE"
     else
-      echo "LAPACK COULD NOT RUN MAKE - CHECK SETUP_FORTRAN_PACKAGES SCRIPT" >&2
+      echo "LAPACK COULD NOT RUN MAKE" >&2
+      cd $ROOTDIR
       return 1
     fi
 
@@ -63,15 +65,28 @@ if [ -z "${IGNORE_FORTRAN_LAPACK_INSTALLATION}" ]; then
     if [ $? -eq 0 ]; then
       echo "LAPACK MAKE INSTALL RUN DONE"
     else
-      echo "LAPACK COULD NOT RUN MAKE INSTALL - CHECK SETUP_FORTRAN_PACKAGES SCRIPT" >&2
+      echo "LAPACK COULD NOT RUN MAKE INSTALL" >&2
+      cd $ROOTDIR
       return 1
     fi
   else
     $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
     -DCMAKE_C_COMPILER=$C_COMPILER --log-level=ERROR ../lapack-3.9.0/
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
 
     make all
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
     make install
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
   fi
   
   cd $ROOTDIR
diff --git a/Cocoa/installation_scripts/setup_hdf5 b/Cocoa/installation_scripts/setup_hdf5
--- a/Cocoa/installation_scripts/setup_hdf5
+++ b/Cocoa/installation_scripts/setup_hdf5
@@ -10,6 +10,10 @@ if [ -z "${C_COMPILER}" ]; then
     echo 'ERROR ENV VARIABLE C_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
+if [ -z "${CMAKE}" ]; then
+    echo 'ERROR ENV VARIABLE MAKE IS NOT DEFINED' >&2
+    return 1
+fi
 if [ -z "${FORTRAN_COMPILER}" ]; then
     echo 'ERROR ENV VARIABLE FORTRAN_COMPILER IS NOT DEFINED' >&2
     return 1
@@ -18,46 +22,58 @@ if [ -z "${MAKE_NUM_THREADS}" ]; then
     echo 'ERROR ENV VARIABLE MAKE_NUM_THREADS IS NOT DEFINED' >&2
     return 1
 fi
+
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
-# ------------------------------ CMAKE LIBRARY  ------------------------------
+# ------------------------------- HDF5 LIBRARY -------------------------------
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
 
-if [ -z "${IGNORE_CMAKE_INSTALLATION}" ]; then
-  echo 'INSTALLING CMAKE - THAT WILL TAKE A WHILE'
+if [ -z "${IGNORE_HDF5_INSTALLATION}" ]; then
+  echo 'INSTALLING HDF5 LIBRARY - THIS MIGHT TAKE A WHILE'
 
-  cd $ROOTDIR/../cocoa_installation_libraries/cmake-3.17.1
+  cd $ROOTDIR/../cocoa_installation_libraries/CMake-hdf5-1.10.10/hdf5-1.10.10
+  
+  rm -f  CMakeCache.txt
+  rm -rf CMakeFiles/
+  rm -rf cocoa_build/
+  mkdir cocoa_build
 
-  if [ -z "${DEBUG_CMAKE_PACKAGE}" ]; then
-    env CC=$C_COMPILER CXX=$CPP_COMPILER ./bootstrap --prefix=$ROOTDIR/.local > /dev/null 2> /dev/null
+  cd cocoa_build
+
+  if [ -z "${DEBUG_HDF5_PACKAGES}" ]; then
+    $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
+      -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER \
+      -DCMAKE_FC_COMPILER=FORTRAN_COMPILER --log-level=ERROR .. > /dev/null 2> /dev/null
     if [ $? -eq 0 ]; then
-      echo "CMAKE BOOTSTRAP RUN DONE"
+      echo "HDF5 CMAKE RUN DONE"
     else
-      echo "CMAKE COULD NOT RUN BOOTSTRAP" >&2
+      echo "HDF5 COULD NOT RUN CMAKE"
       cd $ROOTDIR
       return 1
     fi
 
     make -j $MAKE_NUM_THREADS > /dev/null 2> /dev/null
     if [ $? -eq 0 ]; then
-      echo "CMAKE MAKE RUN DONE"
+      echo "HDF5 MAKE RUN DONE"
     else
-      echo "CMAKE COULD NOT RUN MAKE" >&2
+      echo "HDF5 COULD NOT RUN MAKE"
       cd $ROOTDIR
       return 1
     fi
 
     make install > /dev/null 2> /dev/null
     if [ $? -eq 0 ]; then
-      echo "CMAKE MAKE INSTALL RUN DONE"
+      echo "HDF5 MAKE INSTALL RUN DONE"
     else
-      echo "CMAKE COULD NOT RUN MAKE INSTALL" >&2
+      echo "HDF5 COULD NOT RUN MAKE INSTALL"
       cd $ROOTDIR
       return 1
     fi
   else
-    env CC=$C_COMPILER CXX=$CPP_COMPILER ./bootstrap --prefix=$ROOTDIR/.local
+    $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
+      -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER \
+      -DCMAKE_FC_COMPILER=FORTRAN_COMPILER ..
     if [ $? -ne 0 ];then
       cd $ROOTDIR
       return 1
@@ -68,7 +84,7 @@ if [ -z "${IGNORE_CMAKE_INSTALLATION}" ]; then
       cd $ROOTDIR
       return 1
     fi
-    
+
     make install
     if [ $? -ne 0 ];then
       cd $ROOTDIR
